# Generated by Django 5.1.5 on 2025-03-29 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent_acc',
            fields=[
                ('parent_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=12)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='Parent_profiles')),
            ],
        ),
        migrations.CreateModel(
            name='kid_acc',
            fields=[
                ('kid_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=12)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='Kid_profiles')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='Users.parent_acc')),
            ],
        ),
        
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.kid_acc')),
            ],
        ),
    ]
