# Generated by Django 5.1.5 on 2025-04-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid_acc',
            name='friends',
            field=models.ManyToManyField(blank=True, to='Users.kid_acc'),
        ),
    ]
