# Generated by Django 5.1.5 on 2025-04-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_kid_acc_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
