# Generated by Django 5.1.5 on 2025-05-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='parent_approved',
            field=models.BooleanField(default=False),
        ),
    ]
