# Generated by Django 5.1.5 on 2025-05-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_friendrequest_parent_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid_acc',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, to='Users.kid_acc'),
        ),
    ]
