# Generated by Django 5.1.5 on 2025-05-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_kid_acc_blocked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid_acc',
            name='blocked_users',
        ),
        migrations.AddField(
            model_name='kid_acc',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
