# Generated by Django 5.1.5 on 2025-06-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_remove_kid_acc_blocked_users_kid_acc_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid_acc',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
