# Generated by Django 5.1.5 on 2025-06-24 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_kid_acc_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='parent_approved',
        ),
    ]
