# Generated by Django 5.1.5 on 2025-06-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_remove_friendrequest_parent_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='parent_approved',
            field=models.BooleanField(default=False),
        ),
    ]
