from django.urls import path

from .import views

urlpatterns = [
    path('main',views.main,name='main'),
    path('kid_signup',views.kid_signup,name='kid_signup'),
    path('parent_signup',views.parent_signup,name='parent_signup'),
    path('parent_dashboard',views.parent_dashboard,name='parent_dashboard'),
    path('kid_dashboard',views.kid_dashboard,name='kid_dashboard'),
    path('kid_login',views.kid_login,name='kid_login'),
    path('parent_login',views.parent_login,name='parent_login'),
    path('view_kid_posts',views.view_kid_posts,name='view_kid_posts'),
    path('kids_friends',views.kids_friends,name='kids_friends'),
    path('add_kid',views.add_kid,name='add_kid'),
    path("create_post",views.create_post, name="create_post"),
    path("nav",views.nav, name="nav"),
    path("profile",views.profile, name="profile"),
    path("send_friend_request",views.send_friend_request, name="send_friend_request"),
    path("user_profile/<str:kid_id>/", views.user_profile, name="user_profile"),
    path("send_request/<str:to_kid_id>/", views.send_friend_request, name="send_request"),
    path("handle_request1/<int:request_id>/<str:action>/", views.handle_request1, name="handle_request1"),
    path("handle_request/<int:request_id>/<str:action>/", views.handle_request, name="handle_request"),
    path("edit_profile", views.edit_profile, name="edit_profile"),
    path('comment/<int:post_id>/', views.comment_post, name='comment_post'),
    path("notification/view/<int:notification_id>/", views.view_kid_post_notification, name="view_kid_post_notification"),
    path('parent_logout', views.parent_logout, name='parent_logout'),
    path('kid_logout', views.kid_logout, name='kid_logout'),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    path('edit_parent_profile', views.edit_parent_profile, name='edit_parent_profile'),
    path('change-password', views.change_password, name='change_password'),
    path('chat/', views.chat_page, name='chat_page'),
    path('get_messages/',views.get_messages, name='get_messages'),
    path('like/<int:post_id>/', views.toggle_like, name='toggle_like'),
    path('search_kids/', views.search_kids, name='search_kids'),
    path('kid_change_password/', views.kid_change_password, name='kid_change_password'),
    path('remove_friend/<str:friend_id>/', views.remove_friend, name='remove_friend'),
    path('block_friend/<str:friend_id>/', views.block_friend, name='block_friend'),
    path('handle_parent_request/<int:req_id>/<str:action>/', views.handle_parent_friend_request, name='handle_parent_friend_request'),

    # path('handle_parent_approval/<int:request_id>/<str:action>/', views.handle_parent_approval, name='handle_parent_approval'),
# path('handle_kid_response/<int:request_id>/<str:action>/', views.handle_kid_response, name='handle_kid_response'),
]